function [typedef]=getTypeDefinition()
%
% > 1 Nuclear plants
typedef(1).Key=1;
typedef(end).Type='NUK';                                                         
typedef(end).p_min=0.25;
typedef(end).p_max=1;
typedef(end).p_grad_max=5/100*60; 
typedef(end).c_prod=10.9;%4.54;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=13.33;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 2 Brown coal plants
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='BK';                                                         
typedef(end).p_min=0.4;
typedef(end).p_max=1;
typedef(end).p_grad_max=6/100*60; 
typedef(end).c_prod=24.77;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 3 CHP East (Wärme Tiefstack legacy versio nfor uncoupled optimization)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WT_legacy';                                                         
typedef(end).p_min=0.3;
typedef(end).p_max=1;
typedef(end).p_grad_max=8/100*60;
typedef(end).c_prod=34.5;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).k_add=0;
typedef(end).p_min_t='WT_pmin_2035.txt'; 
typedef(end).p_max_t='WT_pmax_2035.txt'; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=1;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=1;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 4 CHP WEST Block 1 (Wärme Wedel 1 legacy version for uncoupled optimization)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WW1_legacy';                                                         
typedef(end).p_min=0.3;
typedef(end).p_max=1;
typedef(end).p_grad_max=8/100*60;
typedef(end).c_prod=34.5;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).k_add=0;
typedef(end).p_min_t='WW1_pmin_2012.txt';
typedef(end).p_max_t='WW1_pmax_2012.txt'; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=1;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=1;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 5 CHP WEST Block 2 (Wärme Wedel 2 legacy version for uncoupled optimization)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WW2_legacy';                                                         
typedef(end).p_min=0.3;
typedef(end).p_max=1;
typedef(end).p_grad_max=8/100*60;
typedef(end).c_prod=34.5;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).k_add=0;
typedef(end).p_min_t='WW1_pmin_2012.txt'; 
typedef(end).p_max_t='WW2_pmax_2012.txt'; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=1;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=1;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 6 Natural coal plants (condensing unit without heat production)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='SK';                                                         
typedef(end).p_min=0.3;
typedef(end).p_max=1;
typedef(end).p_grad_max=8/100*60;
typedef(end).c_prod=34.5;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 7 Combined cycle gas plants (condensing unit without heat production)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='GuD';                                                         
typedef(end).p_min=0.2;
typedef(end).p_max=1;
typedef(end).p_grad_max=10/100*60; 
typedef(end).c_prod=63.025;
typedef(end).c_start=35/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 8 Gas Turbines 
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='GT';                                                         
typedef(end).p_min=0.2;
typedef(end).p_max=1;
typedef(end).p_grad_max=12/100*60; 
typedef(end).c_prod=122.04;
typedef(end).c_start=19/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 9 Oil steam turbine plants
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='OILDT';                                                         
typedef(end).p_min=0.4;
typedef(end).p_max=1;
typedef(end).p_grad_max=6/100*60; 
typedef(end).c_prod=89.4;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 10 Oil fired gas turbines
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='OILGT';                                                         
typedef(end).p_min=0.2;
typedef(end).p_max=1;
typedef(end).p_grad_max=12/100*60; 
typedef(end).c_prod=80.86;
typedef(end).c_start=19/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 11 Waste incinirator plants
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='GAR';                                                         
typedef(end).p_min=0.4;
typedef(end).p_max=1;
typedef(end).p_grad_max=6/100*60; 
typedef(end).c_prod=3.57;
typedef(end).c_start=59/1.7;
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;                                                  %Überflüssig
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 12 Biomass
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='BM';                                                         
typedef(end).p_min=0;
typedef(end).p_max=1;
typedef(end).p_grad_max=60;
typedef(end).c_prod=2.8;
typedef(end).c_start=0;
typedef(end).T_gen=8.89;
typedef(end).k_add=0;
typedef(end).p_min_t='p_min_biomass.txt'; 
typedef(end).p_max_t='p_max_biomass.txt'; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=1;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 13 Pumped storage Turbine Operation (P_0 > 0)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='PS_G';
typedef(end).p_min=0;
typedef(end).p_max=1;
typedef(end).p_grad_max=60;
typedef(end).c_prod=0;
typedef(end).T_gen=11.429;
typedef(end).e_max=8;                                                     % Maximum Storage energy level in hours (E_max/P_0)
typedef(end).e_min=0;
typedef(end).e_start=4;                                                    % Minimum Storage energy level in hours (E_min/P_0)
typedef(end).eta=1;                                                       % Storage Efficiency 
typedef(end).k_add=1; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=1;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=1;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 14 Pump storage Pump Operation (P_0 < 0)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='PS_C';
typedef(end).p_min=0;
typedef(end).p_max=1;
typedef(end).c_prod=0;
typedef(end).e_max=0;                                                     % Maximum Storage energy level in hours (E_max/P_0)
typedef(end).e_min=0;
typedef(end).e_start=0;                                                    % Minimum Storage energy level in hours (E_min/P_0)
typedef(end).eta=1;                                                       % Storage Efficiency 
typedef(end).k_add=1;                                              % Storage Efficiency 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%% Thermal units for coupled optimization
% > 15 Combined heat and power plant East (HKW Tiefstack)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WT';
typedef(end).p_min=0.5;
typedef(end).p_max=1;
typedef(end).p_grad_max=2/100*60;
typedef(end).c_prod=15.5275;
typedef(end).c_start=59/1.7;
typedef(end).p_q='WT_PQ_Diagramm.txt';
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=1;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).alphaHeatInput=[2.5772 0.21484 0.0020289]; %see ../Vorbereitung/interpolateCHPheatinput.m
typedef(end).site=2;
%
% > 16 Combined cycle heat and power plant (can be used for GuD Tiefstack or GuD Wedel)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='CombinedCycleHeatAndPowerEast';
typedef(end).p_min=0.6;
typedef(end).p_max=1;
typedef(end).p_grad_max=2/100*60; 
typedef(end).c_prod=37.8150;
typedef(end).c_start=35/1.7;
typedef(end).T_gen=8.89;
typedef(end).p_q='CCP_PQ_Diagramm_norm.txt';
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=1;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).alphaHeatInput=[1.8743    0.40612    -0.011729]; %see ../Vorbereitung/interpolateCHPheatinput.m
typedef(end).site=2;
%
% > 17 Combined heat and power plant West, Block 1 (HKW Wedel 1)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WW1';
typedef(end).p_min=0.5;
typedef(end).p_max=1;
typedef(end).p_grad_max=2/100*60;
typedef(end).c_prod=15.5275;
typedef(end).c_start=59/1.7;
typedef(end).p_q='WW1_PQ_Diagramm.txt';
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=1;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).alphaHeatInput=[2.5242 0.31105 -0.042514]; %see ../Vorbereitung/interpolateCHPheatinput.m
typedef(end).site=1;
%
% > 18 Combined heat and power plant West, Block 2 (HKW Wedel 2)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='WW2';
typedef(end).p_min=0.5;
typedef(end).p_max=1;
typedef(end).p_grad_max=2/100*60;
typedef(end).c_prod=15.5275;
typedef(end).c_start=59/1.7;
typedef(end).p_q='WW2_PQ_Diagramm.txt';
typedef(end).T_gen=8.89;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=1;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).alphaHeatInput=[2.5111 0.31821 -0.068279]; %see ../Vorbereitung/interpolateCHPheatinput.m
typedef(end).site=2;
%
% > 19 Peak load boiler Gas
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='PL_G';
typedef(end).c_prod=36.5;
typedef(end).c_start=0;
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 20 Peak load boiler Garbage (always full load by setting cost to zero)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='PL_Gar';
typedef(end).c_prod=0;
typedef(end).c_start=0;
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 21 Peak load Boiler electric
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='PL_El';
typedef(end).c_prod=0;
typedef(end).c_start=0;
typedef(end).epsilon=1;
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=1;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).site=2;
%
% > 22 BHKW
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='BTTP';                                                   %block-type thermal power station
typedef(end).sigma=1.1;                                                     %sigma wird momentan nicht verwendet--> ergibt sich aus P und Q sigma=P/Q
typedef(end).p_grad_max=2/100*60;
typedef(end).p_min=0.1;
typedef(end).p_max=1;
typedef(end).c_prod=1;
typedef(end).c_start=1;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=1;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 23 Heatstorage Out (Q_0 > 0)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='Heat_StOut';
typedef(end).c_prod=1;              %anpassen evtl. leistungsgradient
typedef(end).e_max=19;                                                     % Maximum Storage energy level in hours (E_max/P_0)
typedef(end).e_min=0;                                                    % Minimum Storage energy level in hours (E_min/P_0)
typedef(end).e_start=19/2;                                                    % Minimum Storage energy level in hours (E_min/P_0)
typedef(end).eta=.9;                                                         % Storage Efficiency 
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=1;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=1;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%
% > 24 Heatstorage In (Q_0 < 0)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='Heat_StIn';
typedef(end).c_prod=-1;             %anpassen evtl. leistungsgradient
typedef(end).eta=.9;                                                         % Storage Efficiency 
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=1;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%%
% > 25 Renewable Plants
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='RE';
typedef(end).isPowerProducer=0;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
% > 26 Curtailment unit (is modeled as a negative producer, P_0 < 0, costs are arbitrary high so that it is always the last resort)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='Curt';
typedef(end).p_max=1;
typedef(end).p_min=0;
typedef(end).c_prod=-200;%-5; % most expensive other option is starting up CCP for one hour (about 10 000 MTE) // -1; % if no cost used, pumped storage will be less attractive than curtailment at the end of the horizon
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=1;
%
% > 27 Electricity Imports (modeled with very high costs, can be used if no feasible solution found)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='Import';
typedef(end).p_max=1;
typedef(end).p_min=0;
typedef(end).c_prod=1.5e4; % most expensive other option is starting up CCP for one hour (about 10 000 MTE)
typedef(end).p_grad_max=4/100;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isStateUnit=0;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=0;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isPriBalUnit=0;
typedef(end).isSecBalUnit=0;
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=0;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
typedef(end).isImport=1;
%
% > 28 Demand side storage (DSS)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='Heatpump';
typedef(end).p_max=1;
typedef(end).p_min=0;
typedef(end).c_prod=1e-6;
typedef(end).e_max='e_max_hps_shifted.txt';                                                      % Assumption: Heat pump has a Emax=12h storage capacity and can be used in regime: .2Emax < E < .8Emax for electric grid purposes
typedef(end).e_min=0;
typedef(end).e_start='e_start_hps_shifted.txt';
typedef(end).eta=1;
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=0;
typedef(end).isCHP=0;                                                         
typedef(end).isFossil=0;                                                      
typedef(end).isMicroCHP=0;        
typedef(end).isVarPowLim=0;
typedef(end).isFixLoadCur=0;
typedef(end).isBTTP=0;
typedef(end).isV2G=0;
typedef(end).isStateUnit=0;                                                   
typedef(end).isPriBalUnit=0;                                                  
typedef(end).isSecBalUnit=0;                                                  
typedef(end).isStorage=0;                                                     
typedef(end).isDSS=1;                                                         
typedef(end).isCurt=0;   
typedef(end).T_gen=nan;
%
% > 29 CHP WEST GuD (Wärme Wedel GuD legacy version for uncoupled optimization)
typedef(end+1).Key=length(typedef)+1;
typedef(end).Type='GuDWedel_legacy';                                                         
typedef(end).p_min=0.3;
typedef(end).p_max=1;
typedef(end).p_grad_max=8/100*60;
typedef(end).c_prod=63.025;
typedef(end).c_start=35/1.7;
typedef(end).T_gen=8.89;
typedef(end).k_add=0;
typedef(end).p_min_t='GuDW_pmin_2035.txt'; 
typedef(end).p_max_t='GuDW_pmax_2035.txt'; 
typedef(end).isPowerProducer=1;
typedef(end).isPowerUser=0;
typedef(end).isHeatProducer=0;
typedef(end).isHeatUser=0;
typedef(end).isMustRun=1;
typedef(end).isStateUnit=1;
typedef(end).isPriBalUnit=1;
typedef(end).isSecBalUnit=1;
typedef(end).isFixLoadCur=0;                                               %Powerplant with fixed load curve
typedef(end).isVarPowLim=1;                                                 %Powerplant with time-dependent P_min and P_max
typedef(end).isCHP=0;
typedef(end).isBTTP=0;
typedef(end).isStorage=0;
typedef(end).isDSS=0;
typedef(end).isFossil=1;
typedef(end).isV2G=0;
typedef(end).isCurt=0;
%%
% > Fill definition with nan
allFieldNames=fieldnames(typedef(end-1));
stringFieldNames={'p_q','p_min_t','p_max_t'};
numericFieldNames=setdiff(allFieldNames, stringFieldNames);
for i=1:length(typedef)
   for j=1:numel(numericFieldNames)
       if isempty(typedef(i).(numericFieldNames{j})) 
            typedef(i).(numericFieldNames{j})=nan;
       end
   end
end